name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: seasoned
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/capricorn/capricorn
            git pull origin master
            npm install
            npx prisma db push --accept-data-loss
            npx prisma generate
            npm run build
            
            # Stop old PM2 process (if exists)
            pm2 delete app || true
            
            # Start new PM2 process
            PORT=3001 pm2 start "npm run start" --name app --update-env
      - name: Notify deployment success
        run: echo "Deployment to GCP VM successful!"
